### ISSUE TITLE
Add generics to List

### ISSUE THREAD

**Issue by Cambis** [silverstripeltd/silverstripe-framework-generics#2]
## PR
- https://github.com/silverstripeltd/silverstripe-framework-generics/pull/10

**Comment by GuySartorelli** [comment]
Turns out there are some complications with adding generics to lists in Silverstripe framework:

1. `ArrayList` just doesn't seem to work - at least not with VSCode running intelephense. Or I'm doing it wrong.
    It's more complicated than `DataList` and the like in any case since the model class can be set after instantiation, and the actual list items can be associative arrays (that get later wrapped in `ArrayData`) or `T` directly.
1. `DataObject::get(MyClass::class)` vs `MyClass::get()` is an interesting scenario.
    We can either have:
    1. `DataObject::get(MyClass::class)` result in `DataList<DataObject|MyClass>` and `MyClass::get()` result in `DataList<MyClass|mixed>`, or
    1. `DataObject::get(MyClass::class)` result in `DataList<DataObject>` and `MyClass::get()` result in `DataList<MyClass>`

2 above applies to `DataObject::get()` and `DataObject::get_one()` - if we use generics, we need to either find a way to say "if nothing is passed in, then `T` resolves to `static`", or accept that the return type will be weird. Alternatively (and this is what I've done for now), we can just _not_ use generics in those cases, and use `static` directly instead.

It's a little less precise in the case where you're calling it statically on `DataObject`, but that's the less common scenario anyway so we can probably live with that.

It's also going to give you the wrong type if you go `MyClass::get_one(DifferentClass::class)` - but doing that is an anti-pattern anyway so we can probably just ignore that scenario.

**Comment by GuySartorelli** [comment]
PR merged
